services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=grants
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    env_file: [".env"]
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    ports:
      - "${API_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload

  ingest:
    build: .
    env_file: [".env"]
    environment:
      - PYTHONPATH=/app
      - API_URL=http://api:8080
    working_dir: /app
    depends_on:
      api:
        condition: service_started
    volumes:
      - ./scripts:/app/scripts
      - ./app:/app/app
      - ./packages:/app/packages
    command: python scripts/ingest_any.py
