name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: "Build Docker image (tag: grants-hello-ci)"
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: grants-hello:ci

      - name: Run container
        run: |
          docker run -d --name app -p 8080:8080 grants-hello:ci
          for i in {1..30}; do
            if curl -sSf http://localhost:8080/health >/dev/null; then
              echo "Service is up"; break
            fi
            sleep 1
          done

      - name: Health check
        run: |
          curl -sSf http://localhost:8080/health | tee /tmp/health.json
          curl -sSf http://localhost:8080/ | tee /tmp/root.json

      - name: Show logs on failure
        if: failure()
        run: |
          echo "Container logs:"
          docker logs app || true

      - name: Cleanup
        if: always()
        run: |
          docker rm -f app || true
